language: python
python:
    - "2.6"

branches:
  only:
    - master

notifications:
  email:
    - ben@groovie.org

before_install:
    - sudo apt-get update >/dev/null 2>&1
    - sudo apt-get install libevent-dev libpcre3-dev >/dev/null 2>&1

install:
    - make build
    - make cassandra

script: make test
