language: python
python:
    - "2.6"

branches:
  only:
    - master

notifications:
  email:
    - ben@groovie.org

install:
    - deactivate
    - make -s build
    - make -s cassandra

script: make test
