language: python
python:
    - "2.6"
install:
    - make build
    - make cassandra
script: make test

branches:
  only:
    - master

notifications:
  email:
    - ben@groovie.org

before_install:
    - sudo apt-get update
    - sudo apt-get install libevent-dev libpcre3-dev
