language: python
python:
    - "2.6"

branches:
  only:
    - master

notifications:
  email:
    - ben@groovie.org

install:
    - make build >/dev/null 2>&1
    - make cassandra >/dev/null 2>&1

script: make test
